spring:
  application:
    name: InfoService
  datasource:
    url: jdbc:postgresql://localhost:5434/info_db
    username: info_user
    password: info_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    