spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: AuthService
              uri: http://localhost:8081
              predicates:
                - Path=/smart-appointment/api/auth/**,/smart-appointment/api/users/**

            - id: AppointmentService
              uri: http://localhost:8083
              predicates:
                - Path=/smart-appointment/api/appointments/**

            - id: InfoService
              uri: http://localhost:8082
              predicates:
                - Path=/smart-appointment/api/patients/**,/smart-appointment/api/doctors/**,/smart-appointment/api/blood-types/**,/smart-appointment/api/specialities/**

            - id: ScheduleService
              uri: http://localhost:8084
              predicates:
                - Path=/smart-appointment/api/schedule/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE