server:
  port: 8080

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**

        - id: AppointmentService
          uri: lb://APPOINTMENTSERVICE
          predicates:
            - Path=/appointments/**

        - id: InfoService
          uri: lb://INFOSERVICE
          predicates:
            - Path=/info/**

        - id: ScheduleService
          uri: lb://SCHEDULESERVICE
          predicates:
            - Path=/schedule/**
        
eureka:
# instance:
#   hostname: localhost
  client:
    enable: true
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    instance:
      prefer-ip-address: true

