spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: AuthService
              uri: lb://AUTHSERVICE
              predicates:
                - Path=/smart-appointment/api/auth/**, 
                       /smart-appointment/api/users/**

            - id: AppointmentService
              uri: lb://APPOINTMENTSERVICE
              predicates:
                - Path=/smart-appointment/api/appointments/**

            - id: InfoService
              uri: lb://INFOSERVICE
              predicates:
                - Path=/smart-appointment/api/patients/**, 
                       /smart-appointment/api/doctors/**, 
                       /smart-appointment/api/blood-types/**, 
                       /smart-appointment/api/specialities/**

            - id: ScheduleService
              uri: lb://SCHEDULESERVICE
              predicates:
                - Path=/smart-appointment/api/schedule/**

server:
  port: 8080

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE