spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: auth_user
    password: auth_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8081

eureka:
<<<<<<< HEAD
  instance:
        ip-address: 127.0.0.1
        hostname: localhost
        prefer-ip-address: true
  client:
      enable: true
      service-url:
        default-zone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true
  
=======
  client:
    enable: true
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    instance:
      prefer-ip-address: true
>>>>>>> 3a4e46f5a06713bb06cab62c7d8e0bdbb1ab48fe
