spring.application.name=ScheduleService
server.port =8084
eureka.client.service-url.defaultZone = http:///localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
doctor.service.base-url=${INFO_SERVICE_BASE_URL:http://localhost:8082}
doctor.service.by-id-path=${INFO_SERVICE_BY_ID_PATH:/smart-appointment/api/doctors/{doctorId}}
appointment.service.base-url=${APPOINTMENT_SERVICE_BASE_URL:http://localhost:8083}
appointment.service.admin-appointments-path=${APPOINTMENT_SERVICE_ADMIN_APPOINTMENTS_PATH:/smart-appointment/api/admin/appointments}
appointment.service.users-table-path=${APPOINTMENT_SERVICE_USERS_TABLE_PATH:/smart-appointment/api/users/table}
auth.service.base-url=${AUTH_SERVICE_BASE_URL:http://localhost:8081}
auth.service.validate-path=${AUTH_SERVICE_VALIDATE_PATH:/auth}
